### ISSUE TITLE
Mindmap R3 is up

### ISSUE THREAD

**Issue by theo-armour** [opentecture/mindmapping#1]
@afomi 

![image](https://user-images.githubusercontent.com/547626/40883752-5a04d38c-66b9-11e8-9d80-ad0611b69690.png)

## [Mindmap 3D R3]( https://rawgit.com/opentecture/mindmapping/master/mindmap-3d/r3/mindmap-3d.html )

* Add placards with vendor name and product.
* Add more fields
* Add text entry
	* links to web sites
	* A bit more text about each vendor
* Add file open and file save
* Add second data file
	* Data points for energy analysis apps (random positions for now)

## Wish list

* Sliding menu - so works on phone
* Auto-rotate
* Coming next with UI:
	* Adding data to new cubes / saving data to file for reuse
	* Polylines between data points
* Coming next with the data
	* Data points for file types
	* Data points for viewers
* Add data to new cubes
* Edit positions of existing cubes with pointing device
* And much more ;-)

**Comment by afomi** [comment]
😮 awesome!

pulling this down to play with it!

**Comment by theo-armour** [comment]
no need to pull it just runs: 

https://rawgit.com/opentecture/mindmapping/master/mindmap-3d/r3/mindmap-3d.html

**Comment by afomi** [comment]
ya, I notice that. I noodled through the PushMe/PullYou file. Interesting how it works. I couldn't get it to run locally fully because it relies on `rawgit`, but it is useful and I'll learn more about how to use it more effectively.

I created Issues out of the items in this Issue's "Wish list".

--

In the image attached in this Issue, I see a number of new nodes with Product names, but I was unable to replicate this.  I was able to create a new node, but all fields were `undefined` and I was unable to edit them.  Perhaps I am missing something.

**Comment by theo-armour** [comment]
@afomi 

Thank you for project managing. I will try to get used to this. ;-)

> In the image attached in this Issue, I see a number of new nodes with Product names, but I was unable to replicate this. 

Somehow I lost the button

![image](https://user-images.githubusercontent.com/547626/40884206-579cead4-66c4-11e8-98c5-58667dba1503.png)

Anyway 3.1 is up and 2nd JSON is callable from the button. Also you can use file dialog to open,
 
> I was able to create a new node, but all fields were undefined and I was unable to edit them. 

Yup, no way to fill up those new boxes yet. This will happen.

But I hope to find sites where interesting things can be scraped automatically,

**Comment by afomi** [comment]
@theo-armour - I'll add this back. My mistake.
I kept `rotation`, but though `building-analysis-software-tools` was superfluous, or a leftover.

As for sites that can be scraped, let me know what you find. My go-to for scraping would be Ruby + Nokogiri. 
What'd you have in mind? What tools do you go to for scraping?

**Comment by afomi** [comment]
@theo-armour - I noticed the button has been added back as of https://rawgit.com/opentecture/mindmapping/master/mindmap-3d/r5/mindmap3d.html.

Accordingly, I'll close out this issue.
