### ISSUE TITLE
Mindmap 3D R4

### ISSUE THREAD

**Issue by theo-armour** [opentecture/mindmapping#12]
@opentecture/the-brains 

![image](https://user-images.githubusercontent.com/547626/40907216-fd2c6564-6797-11e8-8e39-b677890e7a61.png)

Ryan and Michal

I note you both like SVG files. So I'm thinking that whatever we have as a 3D mindmap should be able to import SVG files. I'm not sure where this is going, but this is just to let you know that we can import SVG files of significant complexity. And we can have fun with them and attach various behaviors to them in a 3D world and so on.

The code is very messy. I did almost no cleanup. In any case, who knows what will happen in the next release so maybe it does not matter. The big change is that items can move anywhere in 3D space. Once moving the items issues are fixed we should start to have some fun.

## [Mindmap 3D R4]( https://rawgit.com/opentecture/mindmapping/master/mindmap-3d/r4/mindmap-3d.html )

* Very different approach from R3
* Items can be anywhere in 3D space
	* Item positions are editable (albeit with a number of deficiencies )
* Cubes have been replaced with sample SVG files
	* Issue: each SVG is loaded from file each time it's used
	* Animals to be replaced with logos of other similar symbology
* Switch over to trackball controller allows more flexible 3D rotations

## Wishlist
* Add new items and more

**Comment by afomi** [comment]
@theo-armour 

* is it possible to rotate the 3d axes? if so, how? I'm not clear on how to enable the `trackball controller`
* how do the items move? in a 2d plane? or 3d? is it possible/desirable to limit to a 2d plane, then enable the `z` dimension with a button hold (or similar)?

**Comment by afomi** [comment]
@theo-armour - also, I do like the idea of .svg. 

I noticed a comment about how .svg are loading slowly. Therefore, they are not necessary, but a nice to have. Would loading non-svg files improve performance at all? How about non-3d text as well?

**Comment by afomi** [comment]
@theo-armour  - the ability to load an .svg exists in `/build` now. Trackball controls are also included. Thanks!

How we wire up the .svg into a Feature, like a Node Style, can be sketched out in an Issue.
