### ISSUE TITLE
User can create a Mindmap that can also be viewed as a Wardley Map

### ISSUE THREAD

**Issue by theo-armour** [opentecture/mindmapping#13]
@opentecture/the-brains @afomi 

![image](https://user-images.githubusercontent.com/547626/40950303-13631802-6827-11e8-95b9-fae2457a17e8.png)

From the above into something interactive and 3D

## MindMads that are geared up to display Wardley Maps
* Editable by a casual user
* Nodes that look and feel like real things
	* Easy to import and add SVG files
* A multitude of ways of showing the many links and connections between nodes
* Nodes have links to user editable Markdown files
* Noveds can be moved anywhere in 3D space and grouped in a variety of ways
* Nodes can be of different types: people, apps, formats

**Comment by afomi** [comment]
@theo-armour - how do you want to approach this?

My inclination is to split this up into several Issues, and build up a set of small, discrete features that result in the experience you describe above.

Off the top:

* create a new `Map` - later, with the ability to save and load Maps
* default the `type` of Map to `Wardley Map` to start - later being able to set what `type` of Map
* enable user to create `nodes`
* enable user to `link` nodes
* etc.

**Comment by theo-armour** [comment]
Added the text to 

https://github.com/opentecture/mindmapping/blob/master/graphql-3d/README.md
