### ISSUE TITLE
User can create a 2d node in 3d space

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#15]
### Story

As a User
I want to create a 2 node in 3d space
So I can map concepts

### Acceptance Criteria

Given a 3d map exists
When I [interaction to be determined]
Then I see new `node` on the map

**Comment by theo-armour** [comment]
@afomi 
It's in MM 3D R5.1 but got broken somehow. Will fix soon.

![image](https://user-images.githubusercontent.com/547626/41578886-4fd5172c-7349-11e8-9d97-710bb7539d89.png)

**Comment by afomi** [comment]
`/build` now supports 2d planes as Nodes https://opentecture.github.io/mindmapping/build/index.html

![2d](https://user-images.githubusercontent.com/67984/41888023-3a55ed62-78b8-11e8-8cfc-52d922562906.png)
