### ISSUE TITLE
Demo: Connect Edit R1

### ISSUE THREAD

**Issue by theo-armour** [opentecture/mindmapping#17]
@opentecture/the-brains 

### Story

Given multiple nodes - objects of information - in 3D space, we need ways of creating, editing and displaying their logical but intangible connections

### [Connect Edit R1]( https://rawgit.com/opentecture/mindmapping/master/connect-edit/r1/connect-edit.html )

![image](https://user-images.githubusercontent.com/547626/41578076-46b46eb2-7345-11e8-8f25-ccb29368e547.png)

* Creates
	* Two objects
	* Two control points
	* Three types of connecting spline
	* An object that may be moved but has no connections
* Mouseover displays name and position of currently selected object
* All objects may be moved in 3D space

**Comment by afomi** [comment]
Hi @theo-armour, this looks related to https://github.com/opentecture/mindmapping/issues/6.

This demo looks good. What are the three types of polylines? What's the difference between them?

What'd you have in mind in terms of these polylines and the R5 release? How do you think about the integration of these features?

**Comment by afomi** [comment]
Also, mouseover is great with a mouse, but is lacking on a tablet/phone.

Any thoughts on hover features? (This can be elaborated on in an Issue of its own at some point)

**Comment by theo-armour** [comment]
@afomi 

> What are the three types of polylines? What's the difference between them?

https://en.wikipedia.org/wiki/Centripetal_Catmull%E2%80%93Rom_spline

See knot parameterization

See also: https://threejs.org/docs/#api/extras/curves/CatmullRomCurve3

> What'd you have in mind in terms of these polylines and the R5 release? How do you think about the integration of these features?

It's still very early in the design process. I think I'm still gathering kindling. Not really started building the fire yet.

> Also, mouseover is great with a mouse, but is lacking on a tablet/phone.

Good to point this out. 

This code is horridly complex event driven stuff. This may be easy to fix or super hard. Time will tell.

**Comment by afomi** [comment]
Given nodes can be connected with a line, I'll close this one out.

Though, I like the fancy lines - as a nice-to-have later.
