### ISSUE TITLE
How to publish this work?

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#20]
@theo-armour 

I see you're using `PushMePullYou` as a way to publish. I think it offers some nice features and enables navigation easily. Yet, it also adds some overhead, code-wise, provides redundant features to GitHub and GitHub pages, and I can't seem to get it to work for files when I'm developing locally.

I'm curious what other benefits you find it offers, and I'd like to understand how the tools fits into your workflow.

For example, GitHub offers up the site at https://opentecture.github.io/mindmapping by default, and working on the `master` build as its `index.html` would provide users the latest experience, while previous and specific builds can still be accessed from what GitHub provides - for example: 

https://htmlpreview.github.io/?https://github.com/opentecture/mindmapping/blob/master/mindmap-3d/r5/mindmap3d.html

Prepend `https://htmlpreview.github.io/` to any `.html` file when [browsing](https://github.com/opentecture/mindmapping/tree/master/mindmap-3d).

**Comment by theo-armour** [comment]
@afomi 

You raise a bunch of good questions. Too many for me to answer tonight,

### Pretty links
Looks like by deleting the CNAME file you have enabled pretty links to work. Yay!

https://opentecture.github.io/mindmapping was not working but now it is.

## Names
pushMe-pullYou is the name of the organization. There are a bunch of different apps under p-p.

One of my favs:
* [gubgub]( https://pushme-pullyou.github.io/gubgub )

Oops! it has a bug and half of left menu has stopped working. But it's mostly working

The script series I am using for MindMapping 3D is called TooToo.

### TooToo Features

* Uses GitHub pages to host static web content
* Reads Markdown files and renders them as HTML using showdown.js
* Displays HTML files in an Iframe / Many other permutations available as needed
* Uses the GitHub API to obtain a list of file contents
    * Uses that list to build menus and breadcrumbs
   * Therefore is always automatically up to date
   * Sneaky trick to get around issue that JavaScript cannot do a dir listing on your local folders -  but that's OK if your local folder is an exact match of the folders on GitHub
* Checks if a folder has a Read Me file. If so display its contents by default
* Enables permalinks to all files available via location hash
* Same code can be made to work both on GitHub and locally (requires tricks)
* Plays fairly nicely on mobile device
* Files are visible on github.io/github.com/locally

The issue with it is that every web site has slightly different needs, thus the TooToo code never seems to settle down. But the goal is that you could just drop it into any repo and - bingo - you have a baby CMS in a few hundred lines of easy peasy JavaScript.


## htmlpreview.github.io/

I'm a big fan and frequent user.

**Comment by afomi** [comment]
https://github.com/opentecture/mindmapping/pull/22 exists to move away from pushMe-pullYou. I checked out the website, and while clever, seems unnecessary. GitHub provides features to explore and view the repo in a much cleaner way. And, overall, a non-product dependency is removed.

If this inhibits your workflow, please let me know. I'd like to find a good balance. To me, the CMS features are tangential to the mindmap. I'd like to keep the repo concise and meaningful, especially as we get into layering in features.

**Comment by theo-armour** [comment]
@afomi 

This is a very good discussion. I'm enjoying it.  Will try to reply in detail tomorrow.'

**Comment by afomi** [comment]
Per conversation, we will leave PushMe/PullYou in place for generative feature exploration and development. For the integrative product work, I have started a `build` in the `/build` folder.  It is available to view here https://opentecture.github.io/mindmapping/build/.

<img width="912" alt="boxes" src="https://user-images.githubusercontent.com/67984/41815086-156c265a-7715-11e8-9e52-31caf0504676.png">

--- 

I have created an Issue to track the rest of this work https://github.com/opentecture/mindmapping/issues/26
