### ISSUE TITLE
Update 2018-06-25

### ISSUE THREAD

**Issue by theo-armour** [opentecture/mindmapping#28]
@opentecture/the-brains 

### [load stl nasa]( https://opentecture.github.io/mindmapping/connect-edit/load-stl/load-stl-nasa.html )

* STL files from NASA on GitHub

![image](https://user-images.githubusercontent.com/547626/41840252-190bb018-781a-11e8-9e3c-5606b44e7ce2.png)

### [Three.js Basic Template]( https://opentecture.github.io/mindmapping/#templates/threejs-basic.html )

* Very elementary file just to get something simple started
* Useful for developer-facing cookbook/sandbox code samples
* Loads Three.js renderer, scene, camera and controls
* Adds axes helper and cube
* Handles screen being resized
* Sets up requestanimationframe
* Verified by
	* https://validator.w3.org/#validate_by_input
	* http://jshint.com/
	* https://zz85.github.io/mrdoobapproves/

### [Features.md]( https://opentecture.github.io/mindmapping/#FEATURES.md )

* Add text

**Comment by afomi** [comment]
cool stuff from NASA!

I incorporated the .stl loading from GitHub feature into https://opentecture.github.io/mindmapping/build/index.html. The axes helper, cube, resizing, and animation are also included in the build now.

Thanks for these code style links. I will add them to the general README for reference.
