### ISSUE TITLE
Source favicons for each node to use as visual node identifier

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#40]
source: https://github.com/opentecture/mindmapping/issues/31

### Story

As a [PERSONA](PERSONAS.md)
I want to 
So I can 

### Acceptance Criteria

Given 
When 
Then

**Comment by theo-armour** [comment]
Both the GraphQL and the Annotated Bibliography are helping identify and fetch favicons.

So progress is well in hand
