### ISSUE TITLE
Assemblies and components

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#44]
source: https://github.com/opentecture/mindmapping/issues/31

### Assemblies and components

The assembly and disassembly of a number of components into a finished assembly as visualized in 3D is a relatively unexplored territory

The traditional methods - large sheets of paper with numerous numbered drawings - requires expert drawing capabilities and extensive project management in order to produce

**Comment by afomi** [comment]
@theo-armour - fully agree. I'm not sure this is the right repo to explore this work in - though I'm not opposed. Your Jaanga work comes to mind. I think work belongs more in a 3d design tool, which I'm thinking is Spider - please confirm/correct.

I'd love to better understand the extensive project management processes - large paper with number drawings, etc.

**Comment by theo-armour** [comment]
This text is in:

https://github.com/opentecture/mindmapping/blob/master/graphql-3d/README.md

It's just a stub or place holder item. There's nothing currently actionable here.
