### ISSUE TITLE
Augmented Reality and Augmented 3D

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#45]
source: https://github.com/opentecture/mindmapping/issues/31

### Augmented Reality and Augmented 3D

* You want to be able to look at any component in a building or its model and visualize many its aspects such as
	* Building codes
	* Warrantees for the photovoltaic
	* Catalog numbers of the windows
	* Design intents
	* CAD parameters
	* Repair records
	* Kilowatt hours require in December
	* The music currently be streamed to adjacent space

**Comment by afomi** [comment]
@theo-armour - much like https://github.com/opentecture/mindmapping/issues/44 - this is awesome. I'd like to get your thoughts on where this work is best developed and integrated. Spider comes to mind.

I'm happy to move some of these Issues over there.

**Comment by theo-armour** [comment]
@afomi 

graphQL 3D is the tool I want to build to satisfy this item and the previous ones.

It matters little where the data is text, image or 3D data. It all needs ti be acquired, parsed and displayed.

If you know of an existing set of architectural Lego-like components we can play with, assemble and disassemble this would be a great place to start.

**Comment by afomi** [comment]
GraphQL is a backend query language. I don't see the need for it for a long
time.

I think a graph database is really what is desired here.

In terms of all the features for this issue, I think another repo would be
a better place to explore GraphQL. Curious about a use case that justifies
the conventional architecture.

**Comment by theo-armour** [comment]
I don't think there is anything currently actionable here for now - even if the original topic is of interest.

Regarding my use of the term 'graphQL': I probably should not be using it. My use of the tern skews widely from the normal use of the term. We need better words to define the title and purpose of the project.
