### ISSUE TITLE
Problems associated with traditional methods

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#46]
source: https://github.com/opentecture/mindmapping/issues/31

### Problems associated traditional methods

The 'traditional' approach is to grab all the data and suck it into a database. This very often requires a person knowledgeable in setting up databases. This may also require setting up a server and initiating processes that cost money and are not open source.

Data may be comprised of small data sets from a variety of sources. Massaging the data so that it all mixes nicely may be more trouble than it's worth.

**Comment by afomi** [comment]
@theo-armour - I'm not sure what this was in reference too. Or what problem you have in mind. I'd like to anchor this use case with a real user need. 

With API's, it is possible to load data from all sorts of places.

I think a database could be quite valuable, and many developers have the ability to run a basic database. I'm not saying a database should be a requirement, but I'm already resorting to API's for my data needs. Also editing .json files directly may not necessarily be a better user experience than using a service that provides .json.   

In any case, we need to get from .json into the app, and the data will need to be defined at some point - either in a file convention (aka file format) - or more customizable into a specified structure (like a wizard that loads into an array of objects)

Ultimately, is there any work that stems from this Issue? Otherwise, can close.

**Comment by theo-armour** [comment]
nothing actionable here
