### ISSUE TITLE
Create Test Applications

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#47]
## Test Applications

If our effort is to be useful then it should be able to display existing data sets in newly meaningful and informative ways.

The following are links to possible test case ideas

### gbXML Product List

In the beginning we should probably be kicking this one around

* http://gbxml.org/Software_Tools_that_Support_GreenBuildingXML_gbXML
* https://github.com/opentecture/mindmapping/blob/master/data/mindmap-3d-3.json

### Wardley Maps

Is there data for Wardley map in reproducible digital format

* http://wardleypedia.org/mediawiki/index.php/Wardleypedia
* https://medium.com/wardleymaps/on-being-lost-2ef5f05eb1ec
* https://medium.com/wardleymaps
* https://github.com/LeadingEdgeForum/atlas2
	* https://atlas2.wardleymaps.com/

### A Pattern Language

The book includes 253 patterns along with their links to each other, diagrams and more

* https://en.wikipedia.org/wiki/A_Pattern_Language
* https://www.amazon.com/Pattern-Language-Buildings-Construction-Environmental/dp/0195019199
* http://library.uniteddiversity.coop/Ecological_Building/A_Pattern_Language.pdf
* https://archive.org/details/APatternLanguage
* http://caper.ws/patterns/

### Periodic Table

Might be a good place to start

* https://en.wikipedia.org/wiki/Periodic_table
	* A variety of versions available apart from Mendelev's version
* https://www.google.com/search?q=periodic+table&rlz=1C1GCEA_enUS752US752&source=lnms&tbm=isch&sa=X
* 3D: https://www.google.com/search?q=periodic+table+3d&rlz=1C1GCEA_enUS752US752&tbm=isch&tbo=u&source=univ&sa=X

#### Russell's version

* https://en.wikipedia.org/wiki/Walter_Russell
* https://www.google.com/search?q=walter+russell+periodic+table&rlz=1C1GCEA_enUS752US752&tbm=isch&tbo=u&source=univ&sa=X
	* Wow, so many versions
* https://www.quora.com/Why-was-Walter-Russells-version-of-the-periodic-table-not-adopted-by-chemists

### Lego Projects

* http://www.instructables.com/id/3D-Pacman-ghosts/
* https://www.lego.com/biassets/bi/6146259.pdf

### Ikea Product Assembly / Moving Manual Projects

* https://jaanga.github.io/moving-manuals/

Data used in demos sourced from
* http://gbxml.org/Software_Tools_that_Support_GreenBuildingXML_gbXML

**Comment by theo-armour** [comment]
Above data is now in

https://github.com/opentecture/mindmapping/blob/master/graphql-3d/README.md
