### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#48]
source: source: https://github.com/opentecture/mindmapping/issues/31

### GraphQL

Mind maps expressed in a different way

* https://graphql.org/
> GraphQL provides a complete and understandable description of the data in your API,

* https://en.wikipedia.org/wiki/GraphQL
> GraphQL is a data query language developed internally by Facebook in 2012 before being publicly released in 2015. It provides an alternative to REST and ad-hoc web service architectures. It allows clients to define the structure of the data required, and exactly the same structure of the data is returned from the server. It is a strongly typed runtime which allows clients to dictate what data is needed, therefore preventing excessively large amounts of data being returned.

* https://github.com/facebook/graphql
* https://github.com/APIs-guru/graphql-apis
* https://dev-blog.apollodata.com/the-concepts-of-graphql-bc68bd819be3

Have you ever noticed that you very rarely see a graph when you read about GraphQL. Can we change that?

**Comment by theo-armour** [comment]
All above links are in

https://opentecture.github.io/mindmapping/#graphql-3d/README.md

I don't think there's anything particularly actionable here
