### ISSUE TITLE
Xanadu

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#49]
source: https://github.com/opentecture/mindmapping/issues/31

### Xanadu / Ted Nelson

* https://en.wikipedia.org/wiki/Ted_Nelson
* https://en.wikipedia.org/wiki/Project_Xanadu

> Original 17 rules
1. Every Xanadu server is uniquely and securely identified.
2. Every Xanadu server can be operated independently or in a network.
3. Every user is uniquely and securely identified.
4. Every user can search, retrieve, create and store documents.
5. Every document can consist of any number of parts each of which may be of any data type.
6. Every document can contain links of any type including virtual copies ("transclusions") to any other document in the system accessible to its owner.
7. Links are visible and can be followed from all endpoints.
8. Permission to link to a document is explicitly granted by the act of publication.
9. Every document can contain a royalty mechanism at any desired degree of granularity to ensure payment on any portion accessed, including virtual copies ("transclusions") of all or part of the document.
10. Every document is uniquely and securely identified.
11. Every document can have secure access controls.
12. Every document can be rapidly searched, stored and retrieved without user knowledge of where it is physically stored.
13. Every document is automatically moved to physical storage appropriate to its frequency of access from any given location.
14. Every document is automatically stored redundantly to maintain availability even in case of a disaster.
15. Every Xanadu service provider can charge their users at any rate they choose for the storage, retrieval and publishing of documents.
16. Every transaction is secure and auditable only by the parties to that transaction.
17. The Xanadu client–server communication protocol is an openly published standard. Third-party software development and integration is encouraged.

* http://ted.hyperland.com/

**Comment by theo-armour** [comment]
All the above notes are in:

https://opentecture.github.io/mindmapping/#graphql-3d/README.md

There is nothing here that needs acting on for now
