### ISSUE TITLE
Auto-rotate

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#5]

**Comment by afomi** [comment]
@theo-armour - I think I noted this when we spoke.

What did you have in mind? My phone has an auto-rotate setting. Do you have a specific implementation or experience in mind for the map?

**Comment by theo-armour** [comment]
@afomi 

'Auto-rotate' in this context implies the scene rotting around the Z-axis.

Example: https://www.ladybug.tools/spider/gbxml-viewer/

In recent release of MindMap, I have stopped using the camera controller that supports this feature. Therefore, for now the point is moot, and the button will be dropped in the next release.

Mobile device rotation should - fingers crossed - always follow current parameters as set by the user.

**Comment by afomi** [comment]
okay. closing for now. we can re-visit `auto-rotation` in the future, if need be.
