### ISSUE TITLE
Mind Maps

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#50]
source: https://github.com/opentecture/mindmapping/issues/31

---

What's out there that we want to meet or exceed?

### Mind Maps

* https://en.wikipedia.org/wiki/Mind_map
> A mind map is a diagram used to visually organize information. A mind map is hierarchical and shows relationships among pieces of the whole.[1] It is often created around a single concept, drawn as an image in the center of a blank page, to which associated representations of ideas such as images, words and parts of words are added. Major ideas are connected directly to the central concept, and other ideas branch out from those.

* https://www.mindmeister.com/content/features
* http://www.mindmapping.com/
* https://www.mindjet.com/blog/2009/05/the-10-basic-parts-to-a-mind-map/
* https://imindmap.com/software/features/
* http://mindmappingsoftwareblog.com/5-essential-features-you-should-look-for-when-buying-mind-mapping-software/
* https://www.mindmup.com/tutorials/index.html
* https://www.google.com/search?q=mind+map+features&rlz=1C1GCEA_enUS752US752&tbm=isch&tbo=u

Note: Examples mostly always show a single central node. Can we have fun with multiple node groups?

**Comment by afomi** [comment]
@theo-armour - this is a nice deep-dive into Mindmapping research. My question is: what is the destination for this content?

What specifically is the action item (that will complete this `Issue`)? 

I think about [Getting Things Done](https://gettingthingsdone.com/pdfs/gtd_workflow_advanced.pdf) - in terms of the lifecycle of information.

**Comment by theo-armour** [comment]
@afomi 

All the links in this issue are now in here

https://opentecture.github.io/mindmapping/#graphql-3d/README.md
