### ISSUE TITLE
Ideas about Managing Links

### ISSUE THREAD

**Issue by afomi** [opentecture/mindmapping#57]
### Parsing the original [post](https://github.com/opentecture/resources/issues/6#issuecomment-460029778)....

* It would be nice to build a list [of resources] good enough for inclusion here: https://github.com/sindresorhus/awesome
* I am looking for good ways of managing curated lists.
* Very long read me files with naked links, I find tedious and uninformative/uncurated
Workflows for adding links to bookmarks in your browser then getting these links into markdown are complex
* I would like to be able to take a bunch of links from my browser bookmark manager and get them into a markdown file quickly and easily
* I would like to view and manage links with a tree-view menu system

### Story

As a [PERSONA](PERSONAS.md)
I want to 
So I can 

### Acceptance Criteria

Given 
When 
Then

**Comment by theo-armour** [comment]
@afomi 

first pass

I want to access gathered knowledge:
* Retrieve knowledge gathered by others
* 'stand on the shoulders of giants' by looking at knowledge gathered by peeps with domain knowledge
* 'Knowledge' in this case is URLs
* Read any comments added by submitter

I want to do this
* With knowledge embedded in useful records of data
* Using tags to triage the collection of data
* Viewing name, date and other relevant data in the record


Technology that will help
* Data storeable on GitHub.co and retrievable on GitHub.io
* Storing and retrieving tools/apps ditto
* Be editable . manipulable by peeps with entry level skills

So I can
* Export snippets of what I find to 'my space'
* Thank the submitter
* Add comments to the records
* Add tags that focus on
    * General domain knowledge
   * Specific needs for projects we or I are working on (public / private?)
* Add and edit records when I have the authority
* change the world for the better

**Comment by afomi** [comment]
so much to unpack here. this is the right repository for this thinking, but constitutes a lot of work.

lots of this is subjective, and not possible/practical to measure. Curious what potential next steps might be. Or is this just ideation exercise?

**Comment by theo-armour** [comment]
OMG, it turns out that the native format for bookmarks in Chrome and Firefox is JSON.

Both are near identical but FF adds tags

Chrome
* %\AppData\Google\Chrome\User Data into File Explorer.
* In search bar, type Bookmarks, you will see a list of files named Bookmarks and/or Bookmarks.bak.

Firefox
* %APPDATA%\Mozilla\Firefox\Profiles\
* Or use bookmark manager and export as JSON

***

I want to:

* Have add-a-line read and write JSONL bookmarks based on Chrome/FF exportd
* Have see-line ( Celine?) present them to you nicely

**Comment by theo-armour** [comment]
@afomi 

OK to move to Resources repo?

See the effort at: https://github.com/opentecture/resources/tree/master/sandbox

**Comment by afomi** [comment]
This work seems more suitable for this repo.

Resources are for basic, static links.

This repo is a more dynamic playground.

**Comment by afomi** [comment]
@theo-armour - also, because commits are going straight to master, the work you've done is already in the `master` branch of the other repo, which indicates a process smell to me.

**Comment by afomi** [comment]
@theo-armour - I created this PR for your bookmark work. https://github.com/opentecture/mindmapping/pull/58

I'm going to back-out the line commits from this repository, which was only `Markdown`.

**Comment by afomi** [comment]
@theo-armour - the bookmark html/js commits have been force-`deleted` from https://github.com/opentecture/resources. I'll move on to getting this PR merged to this repository.

**Comment by theo-armour** [comment]
@afomi 

Feels like I upset things. Sorry about that.

**Comment by afomi** [comment]
@theo-armour - no problem. Versioned code allows for fixups.

Overall, I'm trying to stay focused on work that provides end-user value.  One-off demo scripts are less-and-less useful as we go, because it is the integration of the functions that provides value. Most libraries provide demos of scripts.

There are INFINITE things that _can_ be done, like .json bookmark marshaling.

Until sharing bookmarks becomes a limiting/blocking factor to other more important work, this is not work I'd have prioritized.

**Comment by afomi** [comment]
@theo-armour - disregarding the rest of this thread, does your bookmark work fulfill the intent of this story? Is this good to close? If not, what specifically needs work?
